Chimoney Readme Translator
Chimoney/chimoney-community-projects pull request #397
Opened 2024-10-01 17:50 UTC by amosayomide05

This translates the English chimoney Readme to another language automatically

2024-10-01 17:51 UTC, amosayomide05 commented
@todak2000 Kindly review this

2024-10-02 12:26 UTC, todak2000 requested changes
Please make PR into Staging not main. This is good work. Thank you and well done @amosayomide05

2024-10-02 12:46 UTC, amosayomide05 commented
> Please make PR into Staging not main. This is good work. Thank you and well done @amosayomide05

I can't find staging

2024-10-04 15:10 UTC, phyleria approved these changes

2024-10-04 15:22 UTC, todak2000 approved these changes

2024-10-23 05:26 UTC, merged