Add technical guide on contributing to Chimoney for Hacktoberfest 2024
Chimoney/chimoney-community-projects pull request #399
Opened 2024-10-01 21:42 UTC by Danbaba1

This pull request closes #392

2024-10-01 21:43 UTC, Danbaba1 commented
@phyleria Please review this pull request.

2024-10-13 06:56 UTC, phyleria commented on chimoney.md
> +Hacktoberfest is an annual event that celebrates open source software and encourages meaningful contributions to open source projects. It's sponsored by DigitalOcean and runs throughout the month of
Hi @Danbaba1, for this part `making a certain number` the number is 4 pull requests, please add that for clarity

2024-10-13 07:01 UTC, phyleria commented on chimoney.md
> +Chimoney follows a code of conduct that ensures a welcoming and inclusive environment for all contributors. Key points include:
In this section, please attach the code of conduct that is here: https://github.com/Chimoney/chimoney-community-projects/blob/main/CODE_OF_CONDUCT.md

2024-10-13 07:04 UTC, phyleria commented on chimoney.md
> +- Join Chimoney's developer community on platforms like Discord or Slack
Hyperlink `Discord` using this link: https://discord.gg/TsyKnzT4qV

2024-10-13 07:04 UTC, phyleria commented on chimoney.md
> +- Participate in discussions and provide feedback on future developments
You can remove this

2024-10-13 07:07 UTC, phyleria commented on chimoney.md
> +- Attend Chimoney webinars or meetups to connect with other contributors
Please rephrase this `- Attend Chimoney webinars or meetups to connect with other contributors` to - Attend Chimoney's events [here](https://lu.ma/Chimoney) to connect with its global community and be updated with the community initiatives.

2024-10-13 07:08 UTC, phyleria commented on chimoney.md
> +- Consider becoming a regular contributor or maintainer
Please remove `maintainer` here

2024-10-13 07:46 UTC, phyleria commented on chimoney.md
> +Chimoney is a fintech platform that provides seamless solutions for global payments, particularly focused on emerging markets. Chimoney also offers various programs like The Chimoney Ambassadorship P
Please change this to 

> Chimoney is a global payouts and infrastructure provider offering an API that businesses, startups, and communities can integrate to handle bulk payouts, rewards, or disbursements in multiple currencies. Chimoney enables users to send money, gift cards, airtime, and other digital assets to recipients worldwide, making it easier for organizations of all sizes, especially those with distributed teams or diverse communities, to manage payments efficiently.

**Key features of Chimoney include:**

- **Bulk payouts**: Organizations can send payments to multiple recipients at once, with recipients able to redeem in their local currencies, saving time and effort.
- **Multi-currency support**: Chimoney supports a range of currencies, including USD, CAD, and NGN, for global transactions.
- **Payment requests**: Chimoney simplifies the process of requesting and receiving payments, making it easier for users to get paid.
- **API integration**: Developers can integrate Chimoney’s API into their systems, automating payment processes and scaling effortlessly.

2024-10-13 07:50 UTC, phyleria requested changes
.

2024-10-13 07:57 UTC, phyleria reviewed
Please submit this within the [Articles](https://github.com/Chimoney/chimoney-community-projects/tree/main/submissions/Articles) folder within submissions

2024-10-13 20:19 UTC, Danbaba1 commented
Okay @phyleria

2024-10-13 20:41 UTC, Danbaba1 commented
@phyleria I have made the changes you requested. Please review my pull request.

2024-10-14 06:49 UTC, phyleria commented on submissions/Articles/optimizing-chimoney-integration.md
> +## Code of Conduct
Please hyperlink the code of conduct instead using the link I provided @Danbaba1

2024-10-14 06:50 UTC, phyleria commented on submissions/Articles/optimizing-chimoney-integration.md
> +- Join Chimoney's developer community on platforms like [Discord](https://discord.gg/TsyKnzT4qV)
Rewrite this `- Join Chimoney's developer community on platforms like [Discord](https://discord.gg/TsyKnzT4qV)` to `- Join Chimoney's developer community on [Discord](https://discord.gg/TsyKnzT4qV)`

2024-10-14 06:52 UTC, phyleria commented on submissions/Articles/optimizing-chimoney-integration.md
> +- Attend Chimoney's events [here](https://lu.ma/Chimoney) to connect with its global community and be updated with the community initiatives.
Rewrite this `- Attend Chimoney's events [here](https://lu.ma/Chimoney) to connect with its global community and be updated with the community initiatives.` to `- Attend Chimoney's events [here](https://lu.ma/Chimoney) to connect with its global community and be updated on the community initiatives.`

2024-10-14 06:55 UTC, phyleria reviewed
Amazing, thank you for the changes! I have added just a few more suggestions and it will be good to go.

Also, can you rename the article from `optimizing-chimoney-integration.md` to `Contributing-to-Chimoney-Hacktoberfest24.md`

2024-10-14 09:29 UTC, Danbaba1 commented
@phyleria I have made the changes you requested. Please review my pull request.

2024-10-14 09:42 UTC, phyleria commented
Great!
 
Please have the code of conduct section as:

> ## Code of Conduct
> Review Chimoney Community's Code of conduct [here](https://github.com/Chimoney/chimoney-community-projects/blob/main/CODE_OF_CONDUCT.md)

Since the code of conduct is now linked, you can remove the sections such as "Our Pledge," "Our Standards," etc. This will allow the reader to proceed directly to the "Benefits of Contributing" section after reviewing the Code of Conduct.

2024-10-14 10:32 UTC, Danbaba1 commented
Okay @phyleria

2024-10-14 10:43 UTC, Danbaba1 commented
@phyleria I have made the changes. Please review my pull request.

2024-10-14 10:48 UTC, phyleria approved these changes
LGTM 🎉

2024-10-14 11:02 UTC, Danbaba1 commented
Thank you so much @phyleria .

2024-10-14 11:31 UTC, Danbaba1 commented
@phyleria Are there any more issues to work on?

2024-10-30 19:28 UTC, merged

2024-10-30 20:12 UTC, Danbaba1 commented
@phyleria Am I getting a chimoney.io reward?

2024-10-30 20:21 UTC, phyleria commented
Hi @Danbaba1,

Yes you will ✅

2024-10-30 20:23 UTC, Danbaba1 commented
@phyleria Thank you so much. I look forward to working on more open source projects with you. If there is any still available before hacktoberfest closes please let me know.

2024-10-30 20:26 UTC, phyleria commented
Yes, I will let you know. Thank you very much for your contributions!

2024-10-30 20:45 UTC, Danbaba1 commented
@phyleria You are welcome.