Developer's Guide to Choosing the Right API for Global Payouts
Chimoney/chimoney-community-projects pull request #408
Opened 2024-10-04 10:42 UTC by ayan-joshi

Added the required article
Closing issue #384 

Have a look @phyleria

2024-10-04 11:02 UTC, phyleria commented
Ok ✅

2024-10-04 14:27 UTC, phyleria commented on submissions/Dev focused articles/GlobalPayoutGuide.md
> +### 6. **XRPL Payments**
Interledger Payment Pointers for Web Monetization.

2024-10-04 14:30 UTC, phyleria commented on submissions/Dev focused articles/GlobalPayoutGuide.md
> +## Getting Started with the Chimoney API
Please reference from this article on `Getting Started with the Chimoney API` part - https://chimoney.io/blogs/the-ultimate-guide-to-simplifying-global-payouts-for-your-business-with-api-solutions/

2024-10-04 14:44 UTC, ayan-joshi commented
@phyleria Made required changes have a look if approved , I'll go to the next one , Thanks !

2024-10-05 13:59 UTC, ayan-joshi commented
> @phyleria Made required changes have a look if approved , I'll go to the next one , Thanks !

@phyleria have a look

2024-10-05 13:59 UTC, ayan-joshi commented
> @phyleria Made required changes have a look if approved , I'll go to the next one , Thanks !

@phyleria have a look

2024-10-07 07:23 UTC, phyleria commented on submissions/Dev focused articles/GlobalPayoutGuide.md
>  ### Services Offered by Chimoney API:
Kindly remove this part

2024-10-07 07:30 UTC, phyleria requested changes
Under other 'Global Payout solutions, kindly remove Stripe. Also please link Paypal, Wise and Payoneer to the comparison articles we have on the footer section at [chimoney.io](https://chimoney.io/) as attached 
![image](https://github.com/user-attachments/assets/a45b7595-ba0a-4983-a586-32f4427870ff)

2024-10-07 07:41 UTC, phyleria requested changes
Kindly replace this `For more information on how to get started with Chimoney, visit the [Chimoney API Documentation](https://chimoney.io). with this `Interested in learning more about how the Chimoney API can streamline your payouts? Book a [demo session](https://chimoney.io/?book_a_demo=1) with us today.`

2024-10-07 07:55 UTC, phyleria commented on submissions/Dev focused articles/GlobalPayoutGuide.md
> +Chimoney's Global Payouts API provides a seamless way for businesses to execute global payments effortlessly. This guide is tailored for developers, featuring step-by-step instructions on how to inte
Please update the following section to the following steps and their description:
- Get Sandbox Access
- Test Your Integration
- Go Live!

2024-10-07 17:15 UTC, ayan-joshi commented
@phyleria made the changes , have a look !

2024-10-07 22:33 UTC, phyleria commented on submissions/Dev focused articles/GlobalPayoutGuide.md
> -- **Stripe** is known for its payment processing capabilities, but it does not offer as many options for payout diversity, such as airtime or gift cards.
Hi @adarsh-jha-dev 

Please add the comparison links in this format `**[Stripe]((https://chimoney.io/using/paypal/for-sending/mass-payments/vs-using/chimoney/)** is known for its payment processing capabilities, but it does not offer as many options for payout diversity, such as airtime or gift cards.`

2024-10-07 22:33 UTC, phyleria commented on submissions/Dev focused articles/GlobalPayoutGuide.md
> +Chimoney's Global Payouts API provides a seamless way for businesses to execute global payments effortlessly. This guide is tailored for developers, featuring step-by-step instructions on how to inte
For this part, please change it to `To get started with the Chimoney API, follow this process:`

2024-10-08 14:32 UTC, ayan-joshi commented
@phyleria made changes !

2024-10-09 09:28 UTC, ayan-joshi commented on submissions/Dev focused articles/GlobalPayoutGuide.md
okay

2024-10-09 11:01 UTC, ayan-joshi commented
@phyleria its done

2024-10-10 02:14 UTC, CBID2 commented
Hey @ayan-joshi. When you link and issue(s) that correspond to your pull request(s), I highly recommend doing this 

```md
## Issue
Closes Issue number (e.g., #0)
```
This will help maintainers manage their issues as it automatically closes PRs.

2024-10-10 02:24 UTC, ayan-joshi commented
> Hey @ayan-joshi. When you link and issue(s) that correspond to your pull request(s), I highly recommend doing this
> 
> ```
> ## Issue
> Closes Issue number (e.g., #0)
> ```
> 
> This will help maintainers manage their issues as it automatically closes PRs.

On the top , I have mentioned the issue it will close @CBID2

2024-10-10 02:29 UTC, CBID2 commented
> > Hey @ayan-joshi. When you link and issue(s) that correspond to your pull request(s), I highly recommend doing this
> 
> > 
> 
> > ```
> 
> > ## Issue
> 
> > Closes Issue number (e.g., #0)
> 
> > ```
> 
> > 
> 
> > This will help maintainers manage their issues as it automatically closes PRs.
> 
> 
> 
> On the top , I have mentioned the issue it will close @CBID2 

I know @ayan-joshi , but the way you currently posted your pull request's number won't appear in the Development section (see attached photo below👇)

![image](https://github.com/user-attachments/assets/1fb0c768-7393-4f31-9645-f4cbccbb0319)

Doing it in the way I mentioned helps with this. Does that clarify things a bit more now?

2024-10-10 02:34 UTC, ayan-joshi commented
> > > Hey @ayan-joshi. When you link and issue(s) that correspond to your pull request(s), I highly recommend doing this
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > ## Issue
> > 
> > 
> > > Closes Issue number (e.g., #0)
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > This will help maintainers manage their issues as it automatically closes PRs.
> > 
> > 
> > On the top , I have mentioned the issue it will close @CBID2
> 
> I know @ayan-joshi , but the way you currently posted your pull request's number won't appear in the Development section (see attached photo below👇)
> 
> ![image](https://private-user-images.githubusercontent.com/105683440/375192124-1fb0c768-7393-4f31-9645-f4cbccbb0319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Mjc4ODcsIm5iZiI6MTcyODUyNzU4NywicGF0aCI6Ii8xMDU2ODM0NDAvMzc1MTkyMTI0LTFmYjBjNzY4LTczOTMtNGYzMS05NjQ1LWY0Y2JjY2JiMDMxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjMzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTJjZTFhNzZjNDdjMGQzZmQwN2U2N2IzYjVjZDgyNGU1M2ZmYWQ4NTVhOTAyOGNlNzFjOGNhYzM5ZWIzM2RlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bA36E2o-aMG2ZFqrXWwGM5Hds74VnarahMTlDZOLKQQ)
> 
> Doing it in the way I mentioned helps with this. Does that clarify things a bit more now?

Okay got it thanks !

2024-10-10 18:30 UTC, phyleria approved these changes

2024-10-10 18:31 UTC, phyleria commented
Thank you so much @ayan-joshi for your work on this 🎉

2024-10-10 19:16 UTC, ayan-joshi commented
> Thank you so much @ayan-joshi for your work on this 🎉

Thanks to you as well @phyleria

2024-10-11 11:14 UTC, ayan-joshi commented
@phyleria By mistake I added images in here now removed successfully have a look please to approve and merge the pr

2024-10-12 13:14 UTC, phyleria approved these changes

2024-10-24 05:07 UTC, merged