add article #383 aligning with the new folder structure
Chimoney/chimoney-community-projects pull request #415
Opened 2024-10-07 16:07 UTC by adarsh-jha-dev

closes #383

2024-10-07 18:03 UTC, adarsh-jha-dev commented
Hey @phyleria , could you please review this whenever you're free.

2024-10-09 08:41 UTC, adarsh-jha-dev commented
@phyleria , any update on this?

2024-10-10 16:13 UTC, adarsh-jha-dev commented
hey @phyleria , tomorrow is the merging day of the week, so is there any update on this? (Sorry If i am being too impatient)

2024-10-12 12:32 UTC, phyleria requested changes
Almost ready for merging @adarsh-jha-dev ! You’ve done a great job, and just a few minor adjustments:

1. Some sections mention “Reference” and “Chimoney API Docs,” but the actual links are missing. Could you kindly link them?  

**Example:**   
```markdown
Visit the [Chimoney API Documentation](https://docs.chimoney.io).
```
2. A few sections come off as slightly formal (e.g., “vital to marketplace success”). A more conversational tone can help better engage the readers.

**Example:**  
- **Instead of:**  
  *"Payouts are vital to marketplace success."*  
- **Try:**  
  *"Seamless payouts help keep your users happy and engaged."*

3. Can you please include a simple code sample demonstrating a payout request using Chimoney’s API? [You can check out an example of how it was done in this blog](https://chimoney.io/blogs/integrating-multicurrency-wallets-a-deep-dive-to-multi-currency-global-payouts/)

That will be all. Sorry for the late review

2024-10-13 05:44 UTC, adarsh-jha-dev commented
Np , I have pushed the changes as requested by you, please review them whenever you're free. Thank you.

2024-10-14 11:19 UTC, adarsh-jha-dev commented
Hey @phyleria , any update on this?

2024-10-14 11:28 UTC, phyleria commented
Hi @adarsh-jha-dev 

I noticed that you used AI for the article and there are quite a few corrections needed. I'll take some time to compile all the feedback into a clear and comprehensive format, so it's easier for you to make the necessary changes. Thanks for following up

2024-10-14 12:05 UTC, adarsh-jha-dev commented
> Hi @adarsh-jha-dev
> 
> I noticed that you used AI for the article (not a bad thing) and there are quite a few corrections needed to make it reader-friendly and cohesive. I'll take some time to compile all the feedback into a clear and comprehensive format, so it's easier for you to make the necessary changes. Thanks for following up

Yeah, I often take help from it, thanks for the feedback. I'll wait.

2024-10-16 07:47 UTC, phyleria commented
I believe with this changes, the article will be good to go. Thanks @adarsh-jha-dev !

2024-10-16 08:00 UTC, adarsh-jha-dev commented
> I believe with this changes, the article will be good to go. Thanks @adarsh-jha-dev !

cool, Thanks @phyleria.

2024-10-16 08:05 UTC, adarsh-jha-dev commented
> I believe with this changes, the article will be good to go. Thanks @adarsh-jha-dev !

so you mean no more changes right? I hope you reviewed the latest one.

2024-10-16 08:07 UTC, phyleria commented
Yeah, I reviewed the latest one. Incase there are any more changes on the one you submit after the changes I will let you know but for now no.

2024-10-16 08:09 UTC, adarsh-jha-dev commented
> Almost ready for merging @adarsh-jha-dev ! You’ve done a great job, and just a few minor adjustments:
> 
> 1. Some sections mention “Reference” and “Chimoney API Docs,” but the actual links are missing. Could you kindly link them?
> 
> **Example:**
> 
> ```
> Visit the [Chimoney API Documentation](https://docs.chimoney.io).
> ```
> 
> 2. A few sections come off as slightly formal (e.g., “vital to marketplace success”). A more conversational tone can help better engage the readers.
> 
> **Example:**
> 
> * **Instead of:**
>   _"Payouts are vital to marketplace success."_
> * **Try:**
>   _"Seamless payouts help keep your users happy and engaged."_
> 
> 3. Can you please include a simple code sample demonstrating a payout request using Chimoney’s API? [You can check out an example of how it was done in this blog](https://chimoney.io/blogs/integrating-multicurrency-wallets-a-deep-dive-to-multi-currency-global-payouts/)
> 
> That will be all. Sorry for the late review

wait,I am a little confused, I have already pushed these changes , I hope you're satisfied with the changes and let me know if anything more is to be done from my end. Thank you!

2024-10-16 08:17 UTC, phyleria commented
Hi @adarsh-jha-dev 

Please check the comment time/day. That was four days ago and you resolved that.

2024-10-16 08:22 UTC, adarsh-jha-dev commented
> Hi @adarsh-jha-dev
> 
> Please check the comment time/day. That was four days ago and you resolved that.
> 
> The changes I have requested are from two hours ago

Exactly, where are the new changes that you requested? I only see that you changed the PR title, what other changes are you talking about? Sorry If I am missing something.

2024-10-16 08:24 UTC, phyleria commented
Oh, I reviewed from codespaces and seems like it didn't reflect on your end, though I can see from my end. Let me resolve that

2024-10-16 08:32 UTC, phyleria requested changes

2024-10-16 08:33 UTC, phyleria commented
Are you able to see the comments now @adarsh-jha-dev?

2024-10-16 08:36 UTC, adarsh-jha-dev commented
> Are you able to see the comments now @adarsh-jha-dev?

yes, thanks for resolving, working on them, will be pushing any moment.

2024-10-16 08:54 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +---
should the entire marked paragraph be replaced or just the first part?

2024-10-16 09:04 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +
Done

2024-10-16 09:05 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +## Why Seamless Payouts Matter for Digital Marketplaces
Done

2024-10-16 09:05 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +1. **Currency and Exchange Rates**: Users in different countries often need payouts in their local currencies. Converting currencies can result in poor exchange rates and fees, making the payout less
Done

2024-10-16 09:06 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +Chimoney’s API supports a variety of currencies and payout methods, including bank transfers, mobile money, digital wallets, gift cards, and cryptocurrency. This flexibility allows you to cater to us
Done.

2024-10-16 09:06 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +
Done.

2024-10-16 09:06 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +
Done.

2024-10-16 09:07 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +
Done.

2024-10-16 09:07 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +
Done.

2024-10-16 09:07 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +## Example Code: Making a Payout Request
Done.

2024-10-16 09:08 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +Create an API key to authenticate your marketplace. This key is used to securely communicate with Chimoney’s servers and manage your payouts.
Done.

2024-10-16 09:28 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +---
I have only replaced the first part? Please let me know if that is fine.

2024-10-16 09:43 UTC, phyleria commented on submissions/Articles/payout-digital-marketplaces.md
> +---
Please replace the whole part

2024-10-16 10:02 UTC, adarsh-jha-dev commented on submissions/Articles/payout-digital-marketplaces.md
> +---
Done.

2024-10-16 14:13 UTC, phyleria approved these changes

2024-10-16 14:22 UTC, adarsh-jha-dev commented
Thanks @phyleria , could you please put the `hacktoberfest-accepted` tag here?

2024-10-16 14:33 UTC, phyleria commented
Done ✅

2024-10-16 14:34 UTC, adarsh-jha-dev commented
> Done ✅

Thanks a lot.

2024-10-24 05:06 UTC, merged